# create an image with nplinker dependencies installed, but not the 
# nplinker code itself
FROM python:3.7-slim-buster

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
# add the paths where conda and bigscape will be installed to PATH
ENV PATH="/app/conda/bin:/app/BiG-SCAPE:${PATH}"

SHELL ["/bin/bash", "-c"]
WORKDIR /app

# copy over some installer/archive files
COPY dockerfiles/Miniconda3-latest-Linux-x86_64.sh \
    dockerfiles/Pfam-A.hmm.gz \
    dockerfiles/bokeh-1.3.5.dev3+5.ge5c1c99e1.dirty-py3-none-any.whl \
    /app/

# use mirrors for apt, much faster than the default
#RUN sed -i -e 's/http:\/\/archive.ubuntu.com\/ubuntu/mirror:\/\/mirrors.ubuntu.com\/mirrors.txt/' /etc/apt/sources.list && \
        # install a few things with apt to get started
RUN apt-get update -y && \
        apt-get install -yq wget curl git && \
        apt-get clean && \
        # clone and set up BiG-SCAPE
        git clone https://git.wur.nl/medema-group/BiG-SCAPE.git && \
        chmod +x BiG-SCAPE/*.py && \
        chmod a+w BiG-SCAPE/domains_color_file.tsv && \
        # install Miniconda in batch mode to /app/conda
        chmod +x Miniconda3-latest-Linux-x86_64.sh && \
        ./Miniconda3-latest-Linux-x86_64.sh -b -p /app/conda && \
        # create a conda env using the spec from BiG-SCAPE repo
        /app/conda/bin/conda env create -f BiG-SCAPE/environment.yml && \
        # within the environment:
        # - extract and process Pfam database
        # - install nplinker deps using conda/pip
        # - install patched version of bokeh
        source activate bigscape && \
        gunzip Pfam-A.hmm.gz && \
        hmmpress Pfam-A.hmm && \
        conda install pip tornado toml networkx progress beautifulsoup4 pandas && \
        pip install httpx xdg natsort sortedcontainers cython && \
        pip install -v /app/bokeh-1.3.5.dev3+5.ge5c1c99e1.dirty-py3-none-any.whl && \
        # try to keep the image size down a bit by removing installers...
        rm -f /app/Miniconda3-latest-Linux-x86_64.sh *.whl && \
        # and packages downloaded by conda 
        rm -fr /app/conda/pkgs && \
        # and the bigscape .git folder
        rm -fr /app/BiG-SCAPE/.git 
