# using the nplinkerbase image, add the nplinker app itself on top 
FROM nplinkerbase:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /app

# clone latest master version using a tag substituted in by build script 
# (otherwise Docker will cache this layer assuming it hasn't changed)
RUN cd /app && git clone --depth 1 --branch TAG https://github.com/sdrogers/nplinker nplinker

ENV LANG "en_GB.UTF-8"
ENV LOCALE "C"
# set a HOME variable because things often break if it's left unset
ENV HOME "/data"
ENV DATA "/data"
# tell the webapp to look for a config called nplinker.toml in /data,
# which should be an external volume
ENV NPLINKER_CONFIG "/data/nplinker.toml"

# unbuffered console output, since the user guide tells people to watch
# for certain messages which may not appear as expected if they get buffered
ENV PYTHONUNBUFFERED "1"

# default bokeh server port
EXPOSE 5006/tcp

# run the webapp
CMD cd /app/nplinker && source activate bigscape && bokeh serve webapp/npapp --dev 
