site_name: NPLinker
site_description: Natural Products Linker
strict: false
site_url: https://nplinker.github.io/nplinker/

theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  icon:
    logo: 'material/library-outline'
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: 'favicon.png'

repo_name: nplinker/nplinker
repo_url: https://github.com/nplinker/nplinker
edit_uri: edit/dev/docs/
extra:
  version:
    provider: mike

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Get Started:
  - Welcome to NPLinker: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Logging: logging.md
  # - Configuration: config.md
  # - NPLinker Architecture: architecture.md
  # - Arranger pipeline: arranger.md
  # - Loader pipeline: loader.md
- Concepts:
  - Working Directory Structure: concepts/working_dir_structure.md
  - Config File: concepts/config_file.md
  - GNPS Data: concepts/gnps_data.md
  - BigScape: concepts/bigscape.md
- Diagrams:
  - Dataset Arranger: diagrams/arranger.md
  - Dataset Loader: diagrams/loader.md
- API Documentation:
  - NPLinker Core:
    - NPLinker: api/nplinker.md
    - Dataset Arranger: api/arranger.md
    - Dataset Loader: api/loader.md
    - Schemas: api/schema.md
    - Utilities: api/utils.md
  - Genomics Data:
    - Abstract Base Classes: api/genomics_abc.md
    - Data Models: api/genomics.md
    - MiBIG: api/mibig.md
    - AntiSMASH: api/antismash.md
    - BigScape: api/bigscape.md
    - Utilities: api/genomics_utils.md
  - Metabolomics Data:
    - Abstract Base Classes: api/metabolomics_abc.md
    - Data Models: api/metabolomics.md
    - GNPS: api/gnps.md
    - Utilities: api/metabolomics_utils.md
  - Strain Data:
    - Data Models: api/strain.md
    - Utilities: api/strain_utils.md
  - Scoring: 
    - Abstract Base Classes: api/scoring_abc.md
    - Scoring Methods: api/scoring_methods.md
    - Data Models: api/scoring.md
    - Utilities: api/scoring_utils.md

markdown_extensions:
# https://python-markdown.github.io/extensions/
- toc:
    permalink: true
- admonition
# https://facelessuser.github.io/pymdown-extensions
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.magiclink
- pymdownx.keys
- pymdownx.snippets: # use files outside of docs folder, syntax is `--8<-- "path/to/file"`
    base_path: [.]

watch:
- docs

plugins:
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- autorefs # https://mkdocstrings.github.io/usage/#cross-references-to-any-markdown-heading
- exclude:
    glob:
    - __pycache__/*
- mkdocstrings:
    handlers:
      python:
        # https://mkdocstrings.github.io/python/usage/#configuration
        paths: [src]
        import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://docs.scipy.org/doc/scipy/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
        options:
          # NOTE: some options are not available for free, e.g. `show_inheritance_diagram` and `summary`. 
          # Members options
          members_order: source
          filters: ["!^_[^_]", "!^__all__$", "!^logger$"] # exclude private objects, "__all__" and "logger" 
          # Docstrings options
          docstring_section_style: list
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_if_no_docstring: true
          # Signatures/annotations options
          show_signature_annotations: true
          signature_crossrefs: true
          separate_signature: true
          # Headings options
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
