site_name: NPLinker
site_description: Natural Products Linker
strict: true
site_url: https://nplinker.github.io/nplinker/

theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
  icon:
    logo: 'material/library-outline'
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: 'favicon.png'

repo_name: nplinker/nplinker
repo_url: https://github.com/nplinker/nplinker
edit_uri: edit/dev/docs/
extra:
  version:
    provider: mike

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Get Started:
  - Welcome to NPLinker: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Logging: logging.md
  # - Configuration: config.md
  # - NPLinker Architecture: architecture.md
  # - Arranger pipeline: arranger.md
  # - Loader pipeline: loader.md
- Concepts:
  - Working Directory Structure: concepts/working_dir_structure.md
  - Config File: concepts/config_file.md
  - GNPS Data: concepts/gnps_data.md
  - BigScape: concepts/bigscape.md
- Diagrams:
  - Dataset Arranger: diagrams/arranger.md
- API Documentation:
  - NPLinker: api/nplinker.md
  - Dataset Arranger: api/arranger.md
  - Dataset Loader: api/loader.md
  - Genomics Data:
    - Data Models: api/genomics.md
    - Base Classes: api/genomics_abc.md
    - MiBIG: api/mibig.md
    - AntiSMASH: api/antismash.md
    - BigScape: api/bigscape.md
    - Utilities: api/genomics_utils.md
  - Metabolomics Data:
    - Data Models: api/metabolomics.md
    - Base Classes: api/metabolomics_abc.md
    - GNPS: api/gnps.md
    - Utilities: api/metabolomics_utils.md
  - Strain Data:
    - Data Models: api/strain.md
    - Utilities: api/strain_utils.md
  - Scoring: api/scoring.md
  - Schemas: api/schema.md
  - General Utilities: api/utils.md

markdown_extensions:
# https://python-markdown.github.io/extensions/
- toc:
    permalink: true
- admonition
# https://facelessuser.github.io/pymdown-extensions
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.magiclink
- pymdownx.snippets: # use files outside of docs folder 
    base_path: [., ./src/nplinker, ./src/nplinker/data]

watch:
- docs

plugins:
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- exclude:
    glob:
    - __pycache__/*
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://docs.scipy.org/doc/scipy/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
        options:
          members_order: source
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_if_no_docstring: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          signature_crossrefs: true
          separate_signature: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
