STRAIN_MAPPINGS_FILENAME = "strain_mappings.json"
GENOME_BGC_MAPPINGS_FILENAME = "genome_bgc_mappings.json"
GENOME_STATUS_FILENAME = "genome_status.json"
GNPS_SPECTRA_FILENAME = "spectra.mgf"
GNPS_MOLECULAR_FAMILY_FILENAME = "molecular_families.tsv"
GNPS_ANNOTATIONS_FILENAME = "annotations.tsv"
GNPS_FILE_MAPPINGS_TSV = "file_mappings.tsv"
GNPS_FILE_MAPPINGS_CSV = "file_mappings.csv"
STRAINS_SELECTED_FILENAME = "strains_selected.json"


DOWNLOADS_DIRNAME = "downloads"
MIBIG_DIRNAME = "mibig"
GNPS_DIRNAME = "gnps"
ANTISMASH_DIRNAME = "antismash"
BIGSCAPE_DIRNAME = "bigscape"
BIGSCAPE_RUNNING_OUTPUT_DIRNAME = "bigscape_running_output"
OUTPUT_DIRNAME = "output"
