loglevel = "DEBUG"
logfile = ""
repro_file = ""
[dataset]
root = "/mnt/archive/nplinker_data/current/carnegie_mibig_27112019"
bigscape_cutoff = 65
[dataset.overrides]
[scoring]
random_count = 1
[scoring.metcalf]
sig_percentile = 99
enabled = true
[scoring.hg]
prob = 0.99
enabled = false
[scoring.likescore]
cutoff = 0.5
enabled = false
