loglevel = "DEBUG"
logfile = ""
repro_file = ""
[dataset]
#root = "/mnt/archive/nplinker_data/current/carnegie_mibig_27112019"
root = "/mnt/archive/nplinker_data/current/crusemann_26112019"
bigscape_cutoff = 30
[dataset.overrides]
[scoring]
[scoring.metcalf]
cutoff = 1.0
enabled = true
standardised = true
[scoring.hg]
prob = 0.99
enabled = false
[scoring.likescore]
cutoff = 0.5
enabled = false
