loglevel = "DEBUG"
logfile = ""
repro_file = ""
[dataset]
root = "H:\\nplinker_data\\current\\carnegie_mibig_27112019"
# root = 'platform:MSV000079284'

[scoring.rosetta]

ms1_tol = 100
ms2_tol = 0.2
score_thresh = 0.55
