name: Build and test Python package

permissions:
  contents: read

on:
  push:
    paths:
      - bin/**
      - src/**
      - tests/**
      - setup.py
      - .github/workflows/build.yml
  pull_request:
    paths:
      - bin/**
      - src/**
      - tests/**
      - setup.py
      - .github/workflows/build.yml
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  smoke_test:
    name: Smoke test on ubuntu for python 3.10
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install build pytest wheel pytest-xdist
      - name: Build the package
        run: 	python -m build
      - name: Install nplinker
        run: |
          pip install $(ls dist/nplinker*.whl)
          install-nplinker-deps --run-on-github
      - name: Run unit tests
        run: pytest -n1 -v tests/unit/genomics/test_runbigscape.py