name: cffconvert

on:
  push:
    branches:
      - main
    paths:
      - CITATION.cff
  pull_request:
    branches:
      - main
    paths:
      - CITATION.cff

jobs:

  verify:
    name: "cffconvert"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out a copy of the repository

      - uses: citation-file-format/cffconvert-github-action@main
        name: Check whether the citation metadata from CITATION.cff is equivalent to that in .zenodo.json
