name: Check code style

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**
      - setup.py
  pull_request:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**
      - setup.py

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install "prospector[with_pyroma]" isort
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --check-only src tests --diff
