name: Check static typing

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**
  pull_request:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install mypy
      # mypy configs are in pyproject.toml
      - name: Check static typing
        run: |
          mypy src tests
